### ISSUE TITLE
read jks file in browser context

### ISSUE THREAD

**Issue by nouknouk** [lenchv/jks-js#14]
Hi,

I'm looking for a JS library suitable to read his files **in the scope of a browser**

More precisely, i wonder be able to code a static webpage (without the need of a backend nodejs or whatever server) in which we can drag n drop a jks file and display the list of keys/certs it contains.

To my understanding, jks-js can currently only be executed with nodejs, am I right ?

**Comment by lenchvolodymyr** [comment]
Hi, @nouknouk ! I haven't tested in browser, but it's likely it won't work. First of all, because of using "Buffer" in InputStream and OutpuStream. And also I'm not sure about "node-forge", but it is used only for jks generated in java  11 and higher, so may be not needed for your case.

I suppose, you should try to use polyfill for buffer, for example this one: https://github.com/toots/buffer-browserify

Try to put it in global context: window.Buffer = require('buffer-browserify');
then bundle it and run in the browser.

Let me  know if it works for you.

**Comment by nouknouk** [comment]
Hi,

I achieved to browserify the `parse-jks` npm module to read (password protected) jks store containing (password protected) private keys.

command to run (on linux):
```
# create new folder
mkdir jkslib
cd jkslib

# initialize a npm project
npm init -y

# install browserify & save
npm i -s browserify

# install the parse-jks module & save
npm i -s parse-jks

# create a simple index.js file
echo "const jks=require('parse-jks'); module.exports=jks;" > index.js

# run browserify
# - input = index.js + npm module parse-jks
# - output = the JS file to load in browser: parse-jks.js

./node_modules/.bin/browserify index.js -s parse-jks > parse-jks.js
```

Then in my javascript code on browser side, I use `Uint8Array` to store raw jks file data.
And it works flawlessly :)

![image](https://user-images.githubusercontent.com/4757213/142736885-0a378136-7132-4c0c-a08e-20f5b39a162c.png)
